# Generated by Django 3.2.6 on 2021-08-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('percentage', models.FloatField(blank=True, default=0)),
                ('flat_amount', models.IntegerField(blank=True, default=None, null=True)),
                ('cash', models.IntegerField(blank=True, default=0)),
                ('expiration_date', models.DateTimeField()),
                ('extension_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DiscountUpTo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('flat_amount', models.IntegerField()),
                ('books', models.ManyToManyField(related_name='DUTbooks', to='book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='DiscountPercent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField()),
                ('books', models.ManyToManyField(related_name='DPbooks', to='book.Book')),
            ],
        ),
    ]
