# Generated by Django 3.2.6 on 2021-08-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('percentage', models.FloatField(blank=True, default=0)),
                ('flat_amount', models.IntegerField(blank=True, default=None, null=True)),
                ('cash', models.IntegerField(default=0)),
                ('expiration_date', models.DateTimeField()),
                ('extension_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'کپن',
                'verbose_name_plural': 'کپن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('percentage', models.FloatField(default=0)),
                ('flat_amount', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تخفیف',
                'verbose_name_plural': 'تخفیف\u200cهاها',
            },
        ),
    ]
