# Generated by Django 3.2.6 on 2021-08-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_alter_discount_flat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='title',
            field=models.CharField(default='test_discount', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='discount',
            name='flat_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
