# Generated by Django 3.2.6 on 2021-08-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_alter_discount_flat_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='cash',
            field=models.IntegerField(default=0),
        ),
    ]
