# Generated by Django 3.2.6 on 2021-08-28 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('publisher', models.CharField(max_length=100, verbose_name='ناشر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('time_add', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('image', models.ImageField(default='covers/blank.jpg', null=True, upload_to='covers/', verbose_name='عکس')),
                ('storage', models.PositiveIntegerField(default=1, verbose_name='موجودی')),
                ('slug', models.SlugField(unique=True, verbose_name='عنوان رسمی برای لینک')),
                ('category', models.ManyToManyField(related_name='book', to='book.Category', verbose_name='دسته\u200cبندی')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount', to='discounts.discount', verbose_name='تخفیف')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
            },
        ),
    ]
