# Generated by Django 3.2.6 on 2021-08-21 11:35

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['<django.db.models.fields.CharField>-<built-in function id>']),
        ),
    ]
