# Generated by Django 3.2.6 on 2021-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20210820_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbook',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
