# Generated by Django 3.2.6 on 2021-08-21 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderbook_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbook',
            name='amount',
        ),
    ]
