# Generated by Django 3.2.6 on 2021-08-21 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_orderbook_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbook',
            name='Order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='cart.order'),
        ),
    ]
