# Generated by Django 3.2.6 on 2021-08-22 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_orderbook_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='Order',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
